      - name: Build AAB
        working-directory: mobile/android
        run: |
          ./gradlew bundleRelease -Pandroid.injected.signing.store.file=app-release.keystore \
          -Pandroid.injected.signing.store.password=changeit \
          -Pandroid.injected.signing.key.alias=unchainednames \
          -Pandroid.injected.signing.key.password=changeit

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: UnchainedNames-AAB
          path: mobile/android/app/build/outputs/bundle/release/*.aab
